/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.ferrybig.javacoding.entitymanager;

import java.lang.reflect.Field;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class DefaultIntegerEntityType<T> extends DefaultEntityType<T> implements IntegerEntityType<T> {

	private final Field primary;
	private final boolean primaryKeyAutogenerated;

	@Override
	public boolean isPrimaryKeyAutogenerated() {
		return primaryKeyAutogenerated;
	}
	
	public DefaultIntegerEntityType(Class<T> clazz) {
		this(clazz, true);
	}

	public DefaultIntegerEntityType(Class<T> clazz, boolean primaryKeyAutogenerated) {
		super(clazz);
		this.primaryKeyAutogenerated = primaryKeyAutogenerated;
		for (Field f : clazz.getDeclaredFields()) {
			Column column = f.getAnnotation(Column.class);
			if (column == null) {
				continue;
			}
			if (column.primaryKey()) {
				primary = f;
				return;
			}
		}
		throw new InvalidEntityDescriptionException("No integer primary field found");
	}

	@Override
	public Map<String, Object> generateWhereClauseForKey(int type) {
		return Collections.singletonMap(primary.getName(), type);
	}

}
